name: Publish Web Pages
on:
  push:
    branches:
      - master
  workflow_dispatch: {}
jobs:
  publish_web_pages:
    name: Publish Web Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
      - uses: actions/cache@v2.1.1
        with:
          path: ~/.pnpm-store/v3
          key: pnpm5-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm5-${{ hashFiles('**/pnpm-lock.yaml') }}
            pnpm5-
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.5.1
          run_install: |
            recursive: true
            args: [ '--frozen-lockfile' ]
      - name: Test
        env:
          SHOW_SPAWN_CMD: 'true'
          CI: 'true'
        run: pnpm run test:ci
      - name: Build
        run: pnpm run build
      - name: Add some files
        run: |
          set -o errexit -o pipefail -o nounset

          # Sponsor
          mkdir -pv dist/.github
          cp -v .github/FUNDING.yml dist/.github/FUNDING.yml

          # License
          cp -v LICENSE* dist/

          # ReadMe
          (
            echo '# Personal Website'
            echo
            echo "Source Code: https://github.com/$GITHUB_REPOSITORY"
          ) > dist/README.md
      - name: Publish Web Pages (https://ksxgithub.github.io)
        env:
          GIT_REPO_URL: https://github.com/KSXGitHub/KSXGitHub.github.io.git
          GIT_USERNAME: KSXGitHub
          GIT_PASSWORD: ${{ secrets.WEBSITE_GIT_PASSWORD }}
          GIT_AUTHOR_NAME: ${{ secrets.WEBSITE_GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.WEBSITE_GIT_AUTHOR_EMAIL }}
        run: pnpm run execute publishWebPages
      - name: Publish Web Pages (https://hoangvankhai.github.io)
        env:
          GIT_REPO_URL: https://github.com/HoangVanKhai/HoangVanKhai.github.io.git
          GIT_USERNAME: KSXGitHub
          GIT_PASSWORD: ${{ secrets.WEBSITE_GIT_PASSWORD }}
          GIT_AUTHOR_NAME: ${{ secrets.WEBSITE_GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.WEBSITE_GIT_AUTHOR_EMAIL }}
        run: pnpm run execute publishWebPages
