name: Publish Web Pages
on:
  push:
    branches:
      - master
  workflow_dispatch: {}
jobs:
  publish_web_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.3
      - uses: actions/setup-node@v1.4.3
        with:
          node-version: 14.x
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.pnpm-store/v3
          key: pnpm5-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm5-${{ hashFiles('**/pnpm-lock.yaml') }}
            pnpm5-
      - uses: pnpm/action-setup@v1.2.0
        with:
          version: ${{ matrix.pnpm }}
          run_install: |
            recursive: true
            args: [ '--frozen-lockfile' ]
      - name: Test
        env:
          SHOW_SPAWN_CMD: 'true'
          CI: 'true'
        run: pnpm run test:ci
      - name: Build
        run: pnpm run build
      - name: Publish Web Pages
        env:
          GIT_REPO_URL: https://github.com/KSXGitHub/KSXGitHub.github.io.git
          GIT_USERNAME: KSXGitHub
          GIT_PASSWORD: ${{ secrets.WEBSITE_GIT_PASSWORD }}
          GIT_AUTHOR_NAME: ${{ secrets.WEBSITE_GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.WEBSITE_GIT_AUTHOR_EMAIL }}
        run: pnpm run execute publishWebPages
